# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

#Notes
#user name for VMs is created as vagrant

#<vagrant box add bento/ubuntu-20.04> to add OS image to internal repository
#<vagrant up> to start VMs (run at the same folder where this file is, or pass file as argument)
#<vagrant halt> to stop VMs
#<vagrant destroy> to remove VMs



#You should only need change the first two variables in this file

#Variables
Number_VMs = 3 #number VMs to launch
PUBLIC_KEY_PATH = "~/vm_key.pub"

READ_PUBLIC_KEY = File.read(File.expand_path(PUBLIC_KEY_PATH)).strip

Vagrant.configure("2") do |config|

 config.vm.box = "bento/ubuntu-20.04"

 config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

 config.vm.provision "shell", inline: <<-SHELL
        echo "#{READ_PUBLIC_KEY}" >> /home/vagrant/.ssh/authorized_keys
        sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/g' /etc/ssh/sshd_config
        sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
        systemctl restart sshd
        apt update
        apt-get install -y vim
      SHELL

  (1..Number_VMs).each do |i|
    config.vm.define "server#{i}" do |node|
      node.vm.hostname = "VM#{i}"
      node.vm.network :private_network, ip: "192.168.56.#{2+i}"
    end
  end

end
